influxdb/up:
	docker compose up influxdb 

influxdb/shell:
	docker exec -it influxdb /bin/bash

telegraf/up:
	docker compose up telegraf

telegraf/bash:
	docker exec -it telegraf /bin/bash

stack/up:
	docker compose up

stack/down:
	docker compose down

stack/restart:
	docker compose restart
