mod float_sink_auto;
mod float_sink_impl;
pub use float_sink_auto::FloatSink;
mod bool_sink_auto;
mod bool_sink_impl;
pub use bool_sink_auto::BoolSink;
mod int_sink_auto;
mod int_sink_impl;
pub use int_sink_auto::IntSink;
mod array_sink_auto;
mod array_sink_impl;
pub use array_sink_auto::ArraySink;
