[package]
name = "esp32-virtual-hal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
embedded-hal = "=1.0.0-alpha.9"
log = "0.4"
